require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "public/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "lib/tasks/**/*"

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10

Rails/HasManyOrHasOneDependent:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - "spec/**/*"

RSpec/NestedGroups:
  Max: 3

RSpecRails/InferredSpecType:
  Enabled: true

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - as


Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false