default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: library_user
  password: library_password

development:
  <<: *default
  database: library_system_development

test:
  <<: *default
  database: library_system_test

production:
  <<: *default
  database: library_system_production
  username: <%= ENV["LIBRARY_SYSTEM_DATABASE_USERNAME"] %>
  password: <%= ENV["LIBRARY_SYSTEM_DATABASE_PASSWORD"] %>
