name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PEM }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        EC2_USER: ubuntu
        EC2_IP: ${{ secrets.EC2_IP }}
      run: |
        ssh -o ServerAliveInterval=60 -i ~/.ssh/id_rsa ${EC2_USER}@${EC2_IP} << 'ENDSSH'
          set -x  # Enable command printing
          cd ~/CloudProject
          echo "Current branch:"
          git branch
          echo "Current commit:"
          git rev-parse HEAD
          echo "Fetching changes..."
          git fetch origin
          echo "Reset to origin/main..."
          git reset --hard origin/main
          echo "New commit:"
          git rev-parse HEAD
          echo "Git status:"
          git status
          
          source $HOME/.rvm/scripts/rvm
          bundle install
          RAILS_ENV=production bundle exec rails assets:precompile
          RAILS_ENV=production bundle exec rails db:migrate
          
          if [ -f tmp/pids/server.pid ]; then
            echo "Stopping existing server..."
            kill -9 $(cat tmp/pids/server.pid)
          fi
          rm -f tmp/pids/server.pid
          
          echo "Starting server..."
          RAILS_ENV=production SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} rails s -b 0.0.0.0 -p 3000 -d
          
          echo "Deployment completed"
         
          echo "Server status:"
          ps aux | grep puma
ENDSSH
