name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.6'
        bundler-cache: true
    
    - name: Test
      run: |
        bundle install
        bundle exec rails test

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PEM }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        EC2_USER: ubuntu
        EC2_IP: ${{ secrets.EC2_IP }}
      run: |
        ssh -o ServerAliveInterval=60 -i ~/.ssh/id_rsa ${EC2_USER}@${EC2_IP} << 'ENDSSH'
          cd ~/CloudProject
          source $HOME/.rvm/scripts/rvm
          git pull origin main
          bundle install
          if [ -f tmp/pids/server.pid ]; then
            kill -9 $(cat tmp/pids/server.pid)
            rm tmp/pids/server.pid
          fi
          RAILS_ENV=production bundle exec rake assets:precompile
          RAILS_ENV=production bundle exec rake db:migrate
          nohup bash -c 'RAILS_ENV=production SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} bundle exec rails s -b 0.0.0.0 -p 3000 -d' > /dev/null 2>&1 &
          echo "Deployment completed"
          sleep 10
        ENDSSH
