name: Ruby CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: cloud
          POSTGRES_PASSWORD: cloud
          POSTGRES_DB: library_system_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      POSTGRES_HOST: localhost
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true

      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Setup test database
        run: |
          bundle install
          bundle exec rails db:test:prepare

      - name: Run tests
        run: bundle exec rspec

      - name: Run security scan
        run: |
          bundle exec brakeman -A -q -w2
